


all: Serveur_CheckIn Application_CheckIn

Serveur_CheckIn: Serveur_CheckIn.c CIMP.h
	gcc Serveur_CheckIn.c -o Serveur_CheckIn -lpthread

Application_CheckIn: Application_CheckIn.c CIMP.h
	gcc Application_CheckIn.c -o Application_CheckIn 

	
