/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package japplication_mail;

import java.io.File;
import javax.mail.*;
import javax.mail.internet.*; 
import javax.activation.*; 
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author didierroth
 */
public class jApplication_Mail extends javax.swing.JFrame {
    private parametre param; 
    private Session sess;
    private File[] piecejointe;
   private threadRcv reception;
    

    public parametre getParam() {
        return param;
    }
    /**
     * Creates new form jApplication_Mails
     */
    public jApplication_Mail() {
        param = new parametre();
        param.load();
        
        initComponents();
        
        reception = new threadRcv(this); 
        reception.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txtf_exp = new javax.swing.JTextField();
        Txtf_dest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txtf_obj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txta_txt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtf_image = new javax.swing.JTextField();
        btn_choisir = new javax.swing.JButton();
        butSend = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Txtf_nbmails = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txtf_nbMailsNL = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_mails = new javax.swing.JList<>();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        refreshMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 0));

        jLabel1.setText("expediteur");

        jLabel2.setText("destinataire");

        Txtf_dest.setText("didierroth@icloud.com");
        Txtf_dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtf_destActionPerformed(evt);
            }
        });

        jLabel3.setText("objet");

        Txtf_obj.setText("test");

        Txta_txt.setColumns(20);
        Txta_txt.setRows(5);
        jScrollPane1.setViewportView(Txta_txt);

        jLabel4.setText("texte");

        txtf_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_imageActionPerformed(evt);
            }
        });

        btn_choisir.setText("Choisir");
        btn_choisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choisirActionPerformed(evt);
            }
        });

        butSend.setText("envoyer");
        butSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSendActionPerformed(evt);
            }
        });

        jLabel7.setText("piece jointes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butSend))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtf_image, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_choisir))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Txtf_obj))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Txtf_dest))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Txtf_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txtf_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txtf_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txtf_obj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_choisir))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSend)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("nombre de mails total");

        Txtf_nbmails.setEditable(false);

        jLabel6.setText("Nombre de mails non lus");

        Txtf_nbMailsNL.setEditable(false);

        lst_mails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_mailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lst_mails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txtf_nbmails, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(Txtf_nbMailsNL))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txtf_nbmails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txtf_nbMailsNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        refreshMenuItem.setMnemonic('d');
        refreshMenuItem.setText("Refresh pop3");
        refreshMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(refreshMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btn_choisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choisirActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
         chooser.setMultiSelectionEnabled(true);
        // Note: source for ExampleFileFilter can be found in FileChooserDemo,
        // under the demo/jfc directory in the JDK.
        int returnVal;
        returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) 
        {
            
            String fnm = "";
            for(File f : chooser.getSelectedFiles())
            {
                System.out.println("You chose to open this file: " + f.getPath());
                fnm = fnm + f.getPath() + ";";
            }
            this.piecejointe = chooser.getSelectedFiles();
            this.txtf_image.setText(fnm);
        }
    }//GEN-LAST:event_btn_choisirActionPerformed

    private void butSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSendActionPerformed
        Properties prop = System.getProperties(); 

        prop.put("mail.smtp.auth", Boolean.toString(param.getAuthentification()));
        prop.put("mail.smtp.starttls.enable", Boolean.toString(param.getTtls()));
        prop.put("mail.smtp.host", param.getSmtpServer());
        prop.put("mail.smtp.port", param.getSmtpPort());
        
        
      
        if(prop.get("mail.smtp.host").equals("smtp.gmail.com"))
        {
            prop.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory"); 
            prop.setProperty("mail.smtp.socketFactory.fallback", "false"); 
            prop.setProperty("mail.smtp.port", "465"); 
            prop.setProperty("mail.smtp.socketFactory.port", "465"); 
        }
        
        if (param.getAuthentification()) 
        {
            
            sess = Session.getInstance(prop, new javax.mail.Authenticator() 
            {
                protected PasswordAuthentication getPasswordAuthentication() 
                {
                    return new PasswordAuthentication(param.getEmail(), param.getPassword());
                }
            });
        } 
        else 
        {
            sess = Session.getDefaultInstance(prop);
        }
       
        
        
        if(this.txtf_image.getText().isEmpty())
        {
           try 
           {
                System.out.println("Création du message texte");
                MimeMessage msg = new MimeMessage(sess);
                if(!param.getAuthentification())
                    msg.setFrom(new InternetAddress(this.Txtf_exp.getText()));
                else
                    msg.setFrom(new InternetAddress(param.getEmail()));
                    
                msg.setRecipient(Message.RecipientType.TO, new InternetAddress(this.Txtf_dest.getText()));
                msg.setSubject(this.Txtf_obj.getText());

                String texte = this.Txta_txt.getText();

                msg.setText (texte);

                System.out.println("Envoi du message");
                Transport.send(msg); 
                System.out.println("Message envoyé");
           } 
           catch (AddressException ex) 
            {
                Logger.getLogger(jApplication_Mail.class.getName()).log(Level.SEVERE, null, ex);
            } 
            catch (MessagingException ex) 
            {
                Logger.getLogger(jApplication_Mail.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       else
       {
            try {
                MimeMessage msg = new MimeMessage (sess);
                
                if(!param.getAuthentification())
                    msg.setFrom(new InternetAddress(this.Txtf_exp.getText()));
                else
                    msg.setFrom(new InternetAddress(param.getEmail()));
                
                msg.setRecipient(Message.RecipientType.TO, new InternetAddress(this.Txtf_dest.getText()));
                msg.setSubject(this.Txtf_obj.getText());
                
                System.out.println("Début construction du multipart"); 
                
                Multipart msgMP = new MimeMultipart();
                // 1ère composante : le texte d'accompagnement
                System.out.println("1ère composante");
                
                MimeBodyPart msgBP = new MimeBodyPart();
                msgBP.setText(this.Txta_txt.getText());
                msgMP.addBodyPart(msgBP);
                
                
                System.out.println("Piece jointe");
                
                for (File f : piecejointe)
                {
                    System.out.println("ajout d'une piece jointe");
                    String nf = f.getPath(); 
                    msgBP = new MimeBodyPart();

                    DataSource so = new FileDataSource (nf); 
                    msgBP.setDataHandler (new DataHandler (so)); 
                    
                    
                    msgBP .setFileName(f.getName()); 
                    msgMP.addBodyPart(msgBP);
                }
                
                msg.setContent(msgMP); 
                System.out.println("Envoi du message"); 
                Transport.send(msg); 
                System.out.println("Message envoyé");
                
            } catch (AddressException ex) {
                Logger.getLogger(jApplication_Mail.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MessagingException ex) {
                Logger.getLogger(jApplication_Mail.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_butSendActionPerformed

    private void txtf_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_imageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_imageActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void Txtf_destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtf_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtf_destActionPerformed

    private void lst_mailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_mailsMouseClicked
        // TODO add your handling code here:
        JList<String> theList = (JList) evt.getSource();
        if (evt.getClickCount() == 2) 
        {
          int index = theList.locationToIndex(evt.getPoint());
          if (index >= 0) {
            Object o = theList.getModel().getElementAt(index);
            System.out.println("Double-clicked on: " + o.toString());
            JOptionPane.showMessageDialog(this,((Mail)o).getPrintableText(),((Mail)o).getSujet(),JOptionPane.NO_OPTION);
          }
        }
        else
        {
            if (SwingUtilities.isRightMouseButton(evt)) 
            {
              int index = theList.locationToIndex(evt.getPoint());
              if (index >= 0) {
                Object o = theList.getModel().getElementAt(index);
                System.out.println("right-clicked on: " + o.toString());
                JOptionPane.showMessageDialog(this,((Mail)o).getPrintableHeader(),((Mail)o).getSujet(),JOptionPane.NO_OPTION);
              }
            }
        }
    }//GEN-LAST:event_lst_mailsMouseClicked

    private void refreshMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMenuItemActionPerformed
        // TODO add your handling code here:
        this.reception.fctrcv();
    }//GEN-LAST:event_refreshMenuItemActionPerformed

    public void SetNbMail(int nb)
    {
        this.Txtf_nbmails.setText(Integer.toString(nb));
    }
    
    public void SetNbMailNL(int nb)
    {
        this.Txtf_nbMailsNL.setText(Integer.toString(nb));
    }
    
    public void SetListMail (DefaultListModel dlm)
    {
        this.lst_mails.setModel(dlm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jApplication_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jApplication_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jApplication_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jApplication_Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jApplication_Mail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Txta_txt;
    private javax.swing.JTextField Txtf_dest;
    private javax.swing.JTextField Txtf_exp;
    private javax.swing.JTextField Txtf_nbMailsNL;
    private javax.swing.JTextField Txtf_nbmails;
    private javax.swing.JTextField Txtf_obj;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btn_choisir;
    private javax.swing.JButton butSend;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> lst_mails;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem refreshMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtf_image;
    // End of variables declaration//GEN-END:variables

}
