/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petraudp;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 *
 * @author didierroth
 */
public class petraUI extends javax.swing.JFrame {
    public Socket cliSock;
    DataOutputStream dos = null;   
    DataInputStream dis = null; 
    StringBuffer message = null;

    /**
     * Creates new form petra
     */
    public petraUI() {
        initComponents();
        this.C_AP.setText("OFF");
        this.C_AP.setForeground(Color.red);  
        
        this.C_CS.setText("OFF");
        this.C_CS.setForeground(Color.red);  
        
        this.C_DE .setText("OFF");
        this.C_DE.setForeground(Color.red);  
        
        this.C_L1 .setText("OFF");
        this.C_L1.setForeground(Color.red);  
        
        this.C_L2.setText("OFF");
        this.C_L2.setForeground(Color.red);  
        
        this.C_PP .setText("OFF");
        this.C_PP.setForeground(Color.red);  
        
        this.C_S .setText("OFF");
        this.C_S.setForeground(Color.red);  
        
        this.C_T.setText("OFF");
        this.C_T.setForeground(Color.red);  
        
        
        try
        {
            cliSock = new Socket("10.59.40.64",50000);
            dos = new DataOutputStream(cliSock.getOutputStream());
            dis = new DataInputStream(cliSock.getInputStream());
        }
        catch(IOException ex)
        {
            System.out.println("Err : "+ex);
        }       
        
        if (cliSock==null || dos==null || dis==null) 
            System.exit(1);
        
            CapteurThread CT = new CapteurThread(this);
        CT.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Capteur = new javax.swing.JLabel();
        Actuateur = new javax.swing.JLabel();
        CutOut1 = new javax.swing.JLabel();
        conveyor1 = new javax.swing.JLabel();
        CutOut2 = new javax.swing.JLabel();
        C_L1 = new javax.swing.JLabel();
        C_L2 = new javax.swing.JLabel();
        Epaisseur = new javax.swing.JLabel();
        C_T = new javax.swing.JLabel();
        Slot = new javax.swing.JLabel();
        C_S = new javax.swing.JLabel();
        StatusChariot = new javax.swing.JLabel();
        C_CS = new javax.swing.JLabel();
        PositionBras = new javax.swing.JLabel();
        C_AP = new javax.swing.JLabel();
        PositionPlongeur = new javax.swing.JLabel();
        C_PP = new javax.swing.JLabel();
        BacEntre = new javax.swing.JLabel();
        C_DE = new javax.swing.JLabel();
        Conveyor2 = new javax.swing.JLabel();
        Ventouse = new javax.swing.JLabel();
        Plongeur = new javax.swing.JLabel();
        Bras = new javax.swing.JLabel();
        Grappin = new javax.swing.JLabel();
        PositionChariot = new javax.swing.JLabel();
        A_C1_ON = new javax.swing.JButton();
        A_C1_OFF = new javax.swing.JButton();
        A_C2_ON = new javax.swing.JButton();
        A_C2_OFF = new javax.swing.JButton();
        A_PV_ON = new javax.swing.JButton();
        A_PV_OFF = new javax.swing.JButton();
        A_PA_H = new javax.swing.JButton();
        A_PA_B = new javax.swing.JButton();
        A_AA_C1 = new javax.swing.JButton();
        A_AA_C2 = new javax.swing.JButton();
        A_GA_AG = new javax.swing.JButton();
        A_GA_LA = new javax.swing.JButton();
        A_CP_BE = new javax.swing.JButton();
        A_CP_KO = new javax.swing.JButton();
        A_CP_C1 = new javax.swing.JButton();
        A_CP_C2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Capteur.setText("Capteurs");

        Actuateur.setText("Actuateurs");

        CutOut1.setText("Cut Out 1 :");

        conveyor1.setText("Conveyor 1");

        CutOut2.setText("Cut Out 2 :");

        C_L1.setText("jLabel6");

        C_L2.setText("jLabel7");

        Epaisseur.setText("Epaisseur :");

        C_T.setText("jLabel9");

        Slot.setText("Slot :");

        C_S.setText("jLabel11");

        StatusChariot.setText("Chariot status");

        C_CS.setText("jLabel13");

        PositionBras.setText("Position Bras :");

        C_AP.setText("jLabel15");

        PositionPlongeur.setText("Position Plongeur :");

        C_PP.setText("jLabel17");

        BacEntre.setText("Bac Entrée Vide :");

        C_DE.setText("jLabel19");

        Conveyor2.setText("Conveyor 2");

        Ventouse.setText("Ventouse");

        Plongeur.setText("Plongeur");

        Bras.setText("Bras");

        Grappin.setText("Grappin");

        PositionChariot.setText("Position Chariot");

        A_C1_ON.setText("ON");
        A_C1_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_C1_ONActionPerformed(evt);
            }
        });

        A_C1_OFF.setText("OFF");
        A_C1_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_C1_OFFActionPerformed(evt);
            }
        });

        A_C2_ON.setText("ON");
        A_C2_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_C2_ONActionPerformed(evt);
            }
        });

        A_C2_OFF.setText("OFF");
        A_C2_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_C2_OFFActionPerformed(evt);
            }
        });

        A_PV_ON.setText("ON");
        A_PV_ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_PV_ONActionPerformed(evt);
            }
        });

        A_PV_OFF.setText("OFF");
        A_PV_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_PV_OFFActionPerformed(evt);
            }
        });

        A_PA_H.setText("Haut");
        A_PA_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_PA_HActionPerformed(evt);
            }
        });

        A_PA_B.setText("Bas");
        A_PA_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_PA_BActionPerformed(evt);
            }
        });

        A_AA_C1.setText("Tapis 1");
        A_AA_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_AA_C1ActionPerformed(evt);
            }
        });

        A_AA_C2.setText("Tapis 2");
        A_AA_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_AA_C2ActionPerformed(evt);
            }
        });

        A_GA_AG.setText("agriper");
        A_GA_AG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_GA_AGActionPerformed(evt);
            }
        });

        A_GA_LA.setText("lacher");
        A_GA_LA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_GA_LAActionPerformed(evt);
            }
        });

        A_CP_BE.setText("Bac Entrée");
        A_CP_BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CP_BEActionPerformed(evt);
            }
        });

        A_CP_KO.setText("Bac KO");
        A_CP_KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CP_KOActionPerformed(evt);
            }
        });

        A_CP_C1.setText("Tapis 1");
        A_CP_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CP_C1ActionPerformed(evt);
            }
        });

        A_CP_C2.setText("Tapis 2");
        A_CP_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CP_C2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BacEntre)
                    .addComponent(Slot)
                    .addComponent(Epaisseur)
                    .addComponent(PositionBras)
                    .addComponent(StatusChariot)
                    .addComponent(CutOut2)
                    .addComponent(CutOut1)
                    .addComponent(PositionPlongeur)
                    .addComponent(Capteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C_CS)
                            .addComponent(C_S))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Plongeur, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bras, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_L1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conveyor1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_L2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Conveyor2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_DE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_T)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ventouse))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_AP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Grappin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C_PP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(PositionChariot)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Actuateur)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(A_CP_C1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(A_CP_BE, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(A_GA_AG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_PA_H, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_PV_ON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_C2_ON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_C1_ON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_AA_C1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_PA_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_PV_OFF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_C2_OFF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_C1_OFF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_GA_LA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_AA_C2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(A_CP_KO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_CP_C2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Actuateur)
                    .addComponent(Capteur))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CutOut1)
                    .addComponent(A_C1_OFF)
                    .addComponent(A_C1_ON)
                    .addComponent(C_L1)
                    .addComponent(conveyor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CutOut2)
                    .addComponent(C_L2)
                    .addComponent(Conveyor2)
                    .addComponent(A_C2_ON)
                    .addComponent(A_C2_OFF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C_T)
                        .addComponent(Ventouse)
                        .addComponent(A_PV_ON)
                        .addComponent(A_PV_OFF))
                    .addComponent(Epaisseur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Plongeur)
                    .addComponent(C_S)
                    .addComponent(Slot)
                    .addComponent(A_PA_H)
                    .addComponent(A_PA_B))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusChariot)
                    .addComponent(C_CS)
                    .addComponent(Bras)
                    .addComponent(A_AA_C1)
                    .addComponent(A_AA_C2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PositionBras)
                    .addComponent(C_AP)
                    .addComponent(Grappin)
                    .addComponent(A_GA_AG)
                    .addComponent(A_GA_LA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PositionPlongeur)
                    .addComponent(C_PP)
                    .addComponent(PositionChariot)
                    .addComponent(A_CP_BE)
                    .addComponent(A_CP_KO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BacEntre)
                    .addComponent(C_DE)
                    .addComponent(A_CP_C1)
                    .addComponent(A_CP_C2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_C1_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_C1_OFFActionPerformed
        fctSend(10);        // TODO add your handling code here:
    }//GEN-LAST:event_A_C1_OFFActionPerformed

    private void A_C2_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_C2_ONActionPerformed
        // TODO add your handling code here:
        fctSend(21);
    }//GEN-LAST:event_A_C2_ONActionPerformed

    private void A_GA_AGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_GA_AGActionPerformed
        // TODO add your handling code here:
        fctSend(61);
    }//GEN-LAST:event_A_GA_AGActionPerformed

    private void A_CP_BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CP_BEActionPerformed
        // TODO add your handling code here:
        fctSend(70);
    }//GEN-LAST:event_A_CP_BEActionPerformed

    private void A_PA_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_PA_BActionPerformed
        // TODO add your handling code here:
        fctSend(41);
    }//GEN-LAST:event_A_PA_BActionPerformed

    private void A_C1_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_C1_ONActionPerformed
        // TODO add your handling code here:
        fctSend(11);
    }//GEN-LAST:event_A_C1_ONActionPerformed

    private void A_C2_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_C2_OFFActionPerformed
        // TODO add your handling code here:
        fctSend(20);
    }//GEN-LAST:event_A_C2_OFFActionPerformed

    private void A_PV_ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_PV_ONActionPerformed
        // TODO add your handling code here:
        fctSend(31);
    }//GEN-LAST:event_A_PV_ONActionPerformed

    private void A_PV_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_PV_OFFActionPerformed
        // TODO add your handling code here:
        fctSend(30);
    }//GEN-LAST:event_A_PV_OFFActionPerformed

    private void A_PA_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_PA_HActionPerformed
        // TODO add your handling code here:
        fctSend(40);
    }//GEN-LAST:event_A_PA_HActionPerformed

    private void A_AA_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_AA_C1ActionPerformed
        // TODO add your handling code here:
        fctSend(50);
    }//GEN-LAST:event_A_AA_C1ActionPerformed

    private void A_AA_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_AA_C2ActionPerformed
        // TODO add your handling code here:
        fctSend(51);
    }//GEN-LAST:event_A_AA_C2ActionPerformed

    private void A_GA_LAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_GA_LAActionPerformed
        // TODO add your handling code here:
        fctSend(60);
    }//GEN-LAST:event_A_GA_LAActionPerformed

    private void A_CP_KOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CP_KOActionPerformed
        // TODO add your handling code here:
        fctSend(72);
    }//GEN-LAST:event_A_CP_KOActionPerformed

    private void A_CP_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CP_C1ActionPerformed
        // TODO add your handling code here:
        fctSend(71);
    }//GEN-LAST:event_A_CP_C1ActionPerformed

    private void A_CP_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CP_C2ActionPerformed
        // TODO add your handling code here:
        fctSend(73);
    }//GEN-LAST:event_A_CP_C2ActionPerformed

    private void fctSend(int x)
    {
        try 
        {
            dos.write(x);
            System.out.println("Int send: "+x);
            
        }
        catch (IOException ex) 
        {
            System.err.println("Err : "+ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_AA_C1;
    private javax.swing.JButton A_AA_C2;
    private javax.swing.JButton A_C1_OFF;
    private javax.swing.JButton A_C1_ON;
    private javax.swing.JButton A_C2_OFF;
    private javax.swing.JButton A_C2_ON;
    private javax.swing.JButton A_CP_BE;
    private javax.swing.JButton A_CP_C1;
    private javax.swing.JButton A_CP_C2;
    private javax.swing.JButton A_CP_KO;
    private javax.swing.JButton A_GA_AG;
    private javax.swing.JButton A_GA_LA;
    private javax.swing.JButton A_PA_B;
    private javax.swing.JButton A_PA_H;
    private javax.swing.JButton A_PV_OFF;
    private javax.swing.JButton A_PV_ON;
    private javax.swing.JLabel Actuateur;
    private javax.swing.JLabel BacEntre;
    private javax.swing.JLabel Bras;
    public javax.swing.JLabel C_AP;
    public javax.swing.JLabel C_CS;
    public javax.swing.JLabel C_DE;
    public javax.swing.JLabel C_L1;
    public javax.swing.JLabel C_L2;
    public javax.swing.JLabel C_PP;
    public javax.swing.JLabel C_S;
    public javax.swing.JLabel C_T;
    private javax.swing.JLabel Capteur;
    private javax.swing.JLabel Conveyor2;
    private javax.swing.JLabel CutOut1;
    private javax.swing.JLabel CutOut2;
    private javax.swing.JLabel Epaisseur;
    private javax.swing.JLabel Grappin;
    private javax.swing.JLabel Plongeur;
    private javax.swing.JLabel PositionBras;
    private javax.swing.JLabel PositionChariot;
    private javax.swing.JLabel PositionPlongeur;
    private javax.swing.JLabel Slot;
    private javax.swing.JLabel StatusChariot;
    private javax.swing.JLabel Ventouse;
    private javax.swing.JLabel conveyor1;
    // End of variables declaration//GEN-END:variables
}
